### ISSUE TITLE
Add rel and about property in the link to the license page

### ISSUE THREAD

**Issue by Photonoxx** [geekitude/piwigo-plugin-simplecopyright#10]
As the plugin seems to evolve again, I would like to suggest adding two properties in the \<a\> tag used to point to the license page.

The first is an about="FULL-SIZE-PICTURE-FILE-COMPLETE-URL"
and the second a rel="license"

That permit to link the license more clearly to the full size picture and improve the presence of full size picture linked to that license in image search filter like in google images.

I hope it could appear useful to add (I add it manually before the new update, but if it could be in the original code, it would be cool).

Thanks in advance
Nicolas

**Comment by geekitude** [comment]
Hi

I totally agree about rel property, I will add it ASAP.

I will have to check how to build the correct URL for about property if I am able to deal with it. :)

**Comment by geekitude** [comment]
@Photonoxx : depending on Piwigo configuration, not everyone has access right to full size pictures and the licence link is also available on pages like Piwigo home or album index so I think it would be more logical to add current URL or website home URL as `about` property. What solution would you prefer?

**Comment by Photonoxx** [comment]
I didn't have checked the option to put the license in the site footer, so I don't understand firstly.

Indeed, I prefer the picture URL for the "about" of the link inserted in the metadata part in the image page. The point is that search engine robots associates the license to the biggest accessible size of the picture (I publish under CC-BY-NC-SA and all the pictures are accessible and full-sized by everyone) and if I filter results of image search with big size+CC license I get my pictures.
At the beginning, I notice my pictures in the results are mainly medium size (as set in my website) and not mainly displayed when license filter was activated.

Alternatively, it may be possible to add an option in the plugin's config to choose which size should be used in about property ?

For the footer, it could be the current or Website URL as I doesn't use it, I have no preference.

Thanks (and sorry for my english - If something is not clear, we can speak french too :>) )

**Comment by geekitude** [comment]
Added a new version with `rel` and `about` properties but I haven't been able to find how to build a direct link to image (and even less with specific size) si the `about` url is current page's url.

I will close the issue but open a new one specifically related to `about` property (but I am afraid I won't be able to fix that on my own).

Don't worry, your eglish is good enough :)
Piwigo being an international project it is better to stick to english when possible here but there's nothing wrong to add details in french when needed though.
