### ISSUE TITLE
Using current page URL as `about` property might not be optimal

### ISSUE THREAD

**Issue by geekitude** [geekitude/piwigo-plugin-simplecopyright#14]
This is related to issue #10 

@Photonoxx wanted a direct link to full size image

I think a setting should be added to select `about` target but I have no idea on the way to build the corresponding links.

**Comment by Photonoxx** [comment]
Hi,

In the image.php of the previous plugin, I add a line after the line which set $filename=$row['path']; (actual line 23)

I add this : 
```
//photonoxx
	$persoabout=preg_replace('/\.\//','https://www.photolib.fr/', $filename, 1);
```
And I use $persoabout as about property value (as indeed the new $simplecr_about variable).

I don't know how to get the website root URL in PHP, but it could be set manually in the plugin settings, may be or there already an existing variable that contain this information in Piwigo ?

**Comment by Photonoxx** [comment]
I made some try and I get an apparently fonctionnal code without adding website root URL manually :+1: 

In main.inc.php

instead of code starting at line 77 I have this (I don't clean yet the commented lines) :
```
// Prepare links 'about' attribute
        //$simplecr_about = ' about="';
        // Append protocol
        if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
            $simplecr_about .= 'https://';
        } else {
            $simplecr_about .= 'http://';
        }
        // Append the host(domain name, ip) to the URL
        $simplecr_about .= $_SERVER['HTTP_HOST'];
        // Append the requested resource location to the URL
        //$simplecr_about .= $_SERVER['REQUEST_URI'];
        // Add final double quote
        //$simplecr_about .= '"'; 
```

In image.php I add this at line 24 (after $filename setting) : 
```
//photonoxx
	$simplecr_about .=preg_replace('/\.\//','/', $filename, 1);
```
And after, instead of : 
`'.$simplecr_about.'`
in template definition, I use : 
` about="'.$simplecr_about.'"  `

for each kind of license.

That work for the original picture file, but if it is wanted to use different size variant of pictures, there's something else to do.

Anyway thanks for your work.

**Comment by geekitude** [comment]
That's a first step, I'll work on that for next release, thanks.

**Comment by geekitude** [comment]
Fixed with brand new 12.c version : added a setting to use original image url for `about` property with a warning.

**Comment by geekitude** [comment]
Pretty much screwed up everything with too many changes at once in 12.c version.
Reverted code to 12.b version.

Will take more time for all those changes.

**Comment by geekitude** [comment]
New setting reintroduced with latest release

**Comment by Photonoxx** [comment]
Sorry for the late answer, but I just installed the last release and once setting enabled, it works perfectly, thanks for that !

Nicolas

**Comment by geekitude** [comment]
Thanks for the feedback.

Simon
