### ISSUE TITLE
Broken Creative Commons icons in image.php

### ISSUE THREAD

**Issue by davidpwhelan** [geekitude/piwigo-plugin-simplecopyright#18]
This is a really nice plugin.  I noticed that it was showing up on the Piwigo picture.php page fine but that the CC images were broken.  I looked at the simple copyright/image.php file and all the CC images were at ../../../plugins.  I edited the file to change the image urls to ./plugins and that seems to have fixed it.  This could be because I installed Piwigo below the root of the site?  Not sure if this is a bug or needs to be fixed or if is unique to me.  Thanks for creating the plugin.

**Comment by geekitude** [comment]
Hi
I changed from "plugins/..." to "../../../pugins" to fix the same image problem on one of my Piwigo galleries (had no problem before that on test site but had the issue when downloading plugin to production site).

I will check if "./plugins" works better on both sides.

Thanks for the feedback

**Comment by geekitude** [comment]
The issue most probably comes from my server.
Fix coming soon.

**Comment by geekitude** [comment]
Fixed in 12.i version
