### ISSUE TITLE
Not supporting Bootstrap Darkroom

### ISSUE THREAD

**Issue by hesyifei** [geekitude/piwigo-plugin-simplecopyright#5]
If "Picture info display position" is set to "Card grid below the image" with the Bootstrap Darkroom theme, the copyright info will not be added, as it uses `id="info-content" class="d-flex flex-column">` instead of `class="imageInfoTable">`.

I have to change the replace code
```php
    $search = '#id="info-content" class="d-flex flex-column">#';

    // Replacement to add Simple Copyright default copyright...
    $replacement = 'id="info-content" class="d-flex flex-column">
    <div id="simplecr" class="imageInfo">
        <dl class="row mb-0">
            <dt class="col-sm-5">{\'Copyright\'|@translate}</dt>
            <dd class="col-sm-7">
                {$MEDIA_CR}
            </dd>
        </dl>
    </div>';
```
but hopefully there could be a more elegant solution.

**Comment by geekitude** [comment]
Solved by 7tonin here : https://github.com/geekitude/piwigo-plugin-simplecopyright/pull/6/commits/6caf9ba72303f8d0c433a210c7a3b099fd659bde
