### ISSUE TITLE
Version 11 compatible?

### ISSUE THREAD

**Issue by bdale** [geekitude/piwigo-plugin-simplecopyright#8]
We've been using this plugin happily, but it's not marked as compatible with Piwigo 11.  Does anyone know if it will work?  It's one of a shrinking set of modules we use not explicitly marked as compatible with 11 that are keeping us from upgrading.

**Comment by 7tonin** [comment]
Looks easy to ease compatibility
https://github.com/geekitude/piwigo-plugin-simplecopyright/pull/9

**Comment by geekitude** [comment]
Hi
Really sorry for never answering.
I stayed away from Piwigo for quite a long time.
